import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AreaChart,Area,LineChart,Line,BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
import {Activity,AlertTriangle,ArrowUpRight,BarChart3,BrainCircuit,Factory,Gauge,GitBranch,Leaf,Lightbulb,Network,Play,RefreshCw,Settings2,ShieldCheck,SlidersHorizontal,Sparkles,Zap} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'';
const fallback={kpi:{sec:578.4,baselineSec:610,energyToday:4820,productionToday:8.34,quality:98.2,co2Avoided:37.2,energyReductionPct:5.2},telemetry:Array.from({length:24},(_,i)=>({timestamp:`${i}`,productionTons:7.2+(i%5)*.4,energyKwh:420+(i%7)*22,sec:558+(i%8)*8,furnaceIdleMin:7+(i%5),compressorBar:6.5+(i%4)*.2,motorLoadPct:70+i%12,powerFactor:.94,qualityPct:98,downtimeMin:5})),alerts:[],recommendations:[]};
const fallbackAlerts=[{id:'A-104',severity:'CRITICAL',asset:'Induction Furnace #02',title:'SEC drift above production baseline',detail:'Energy intensity is 8.6% above expected for the current batch profile.',impactKwh:184,confidence:94},{id:'A-098',severity:'WARNING',asset:'Compressor Train',title:'Pressure setpoint is wasting energy',detail:'Pressure is 0.9 bar above the modeled optimum band.',impactKwh:71,confidence:91},{id:'A-091',severity:'INFO',asset:'Casting Cell',title:'Idle energy opportunity detected',detail:'Short gaps between heats can be scheduled to reduce idle thermal losses.',impactKwh:42,confidence:87}];
const fallbackRecs=[{id:'R-01',priority:'HIGH',title:'Reduce furnace idle window',rationale:'Trim idle operation from 12.4 → 8.0 min while preserving heat-cycle constraints.',secReductionPct:3.1,annualSavingInr:198000,paybackMonths:4.2,confidence:93},{id:'R-02',priority:'HIGH',title:'Optimize compressor pressure',rationale:'Move the pressure setpoint into the 6.5–6.8 bar efficiency band.',secReductionPct:1.8,annualSavingInr:116000,paybackMonths:3.7,confidence:91},{id:'R-03',priority:'MEDIUM',title:'Sequence high-load batches',rationale:'Cluster compatible batches to reduce warm-up and transition losses.',secReductionPct:1.4,annualSavingInr:92000,paybackMonths:5.1,confidence:84}];
function money(n){return '₹'+new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(n)}
function App(){
 const [tab,setTab]=useState('command'); const [data,setData]=useState(fallback); const [live,setLive]=useState(false); const [sim,setSim]=useState({idle:8,pressure:6.7,cycle:32,target:8.3}); const [simOut,setSimOut]=useState(null);
 const load=async()=>{if(!API){setLive(false);setData(d=>({...fallback,...d,alerts:fallbackAlerts,recommendations:fallbackRecs}));return}try{const r=await fetch(`${API}/overview`);if(!r.ok)throw Error();const j=await r.json();setData(j);setLive(true)}catch{setLive(false);setData(d=>({...fallback,...d,alerts:fallbackAlerts,recommendations:fallbackRecs}))}};
 useEffect(()=>{load();const t=setInterval(load,6000);return()=>clearInterval(t)},[]);
 const alerts=data.alerts?.length?data.alerts:fallbackAlerts, recs=data.recommendations?.length?data.recommendations:fallbackRecs;
 const chart=useMemo(()=>data.telemetry.map((x,i)=>({name:i%6===0?`${i}:00`:'',sec:Number(x.sec?.toFixed?.(1)||x.sec),energy:Math.round(x.energyKwh),prod:Number(x.productionTons?.toFixed?.(1)||x.productionTons)})),[data]);
 const simulate=async()=>{if(API){try{const q=new URLSearchParams(sim);const r=await fetch(`${API}/simulate?${q}`);if(r.ok){setSimOut(await r.json());return}}catch{}}const projected=548+Math.max(0,sim.idle-8)*1.9+Math.max(0,sim.pressure-6.7)*10.5+Math.max(0,sim.cycle-32)*.75;const red=Math.max(0,(610-projected)/610*100);setSimOut({projectedSec:projected,energyReductionPct:red,co2ReductionKg:red/100*80000*.71,annualSavingInr:red/100*80000*8,qualityConstraintMet:sim.cycle>=30&&sim.cycle<=38})};
 return <div className="app">
  <aside className="sidebar"><div className="brand"><div className="brandMark"><Zap size={19}/></div><div><b>FactorySense</b><span>ENERGY INTELLIGENCE</span></div></div><div className="plant"><span className="pulse"/> PLANT ONLINE <small>IND-04</small></div><nav>{[['command','Command Center',Gauge],['twin','Digital Twin',Network],['analytics','Energy Analytics',BarChart3],['ai','AI Control Room',BrainCircuit],['sim','What-if Lab',SlidersHorizontal],['roi','Savings & ROI',Leaf]].map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={18}/>{label}{id==='ai'&&<i>3</i>}</button>)}</nav><div className="sidebarFoot"><div className="edge"><span><span className="dot"/> Edge gateway</span><b>MQTT · OPC-UA</b></div><div className="version">FACTORYSENSE OS <strong>2.0</strong></div></div></aside>
  <main className="main"><header><div><div className="crumb">SCHNEIDER CHALLENGE 04 <span>/</span> SMART MANUFACTURING</div><h1>{tab==='command'?'Factory Command Center':tab==='twin'?'Live Factory Digital Twin':tab==='analytics'?'Energy Intelligence':tab==='ai'?'AI Control Room':tab==='sim'?'Optimization What-if Lab':'Savings & Deployment'}</h1><p>{tab==='command'?'Production-aware energy optimization for Indian SME manufacturing.':tab==='twin'?'A living view of energy, process and production state.':tab==='analytics'?'Understand what should have happened — and why actual consumption moved.':tab==='ai'?'Every alert carries evidence, impact and an operator-safe action.':tab==='sim'?'Change operating conditions before changing the factory.':'Translate every optimization into kWh, rupees, carbon and payback.'}</p></div><div className="topActions"><span className={live?'live':'demo'}><span/> {live?'LIVE API':'SIMULATION MODE'}</span><button className="iconBtn" onClick={load}><RefreshCw size={17}/></button><button className="avatar">MR</button></div></header>
   {tab==='command'&&<Command data={data} chart={chart} alerts={alerts} recs={recs} setTab={setTab}/>} {tab==='twin'&&<Twin/>} {tab==='analytics'&&<Analytics chart={chart} data={data}/>} {tab==='ai'&&<AI alerts={alerts} recs={recs}/>} {tab==='sim'&&<Simulator sim={sim} setSim={setSim} out={simOut} run={simulate}/>} {tab==='roi'&&<ROI data={data}/>} 
  </main></div>
}
function Card({children,className=''}){return <section className={`card ${className}`}>{children}</section>}
function KPI({label,value,unit,delta,icon:Icon}){return <Card className="kpi"><div className="kpiTop"><span>{label}</span><div className="miniIcon"><Icon size={16}/></div></div><div className="kpiVal">{value}<em>{unit}</em></div><div className="delta">{delta}</div></Card>}
function Command({data,chart,alerts,recs,setTab}){return <div className="page"><div className="kpis"><KPI label="Specific Energy" value={data.kpi.sec} unit="kWh/t" delta={`↓ ${data.kpi.energyReductionPct}% vs baseline`} icon={Gauge}/><KPI label="Energy today" value={(data.kpi.energyToday/1000).toFixed(2)} unit="MWh" delta="−8.4% vs expected" icon={Zap}/><KPI label="Production" value={data.kpi.productionToday} unit="t" delta="Throughput on target" icon={Factory}/><KPI label="Quality" value={data.kpi.quality} unit="%" delta="Within control limits" icon={ShieldCheck}/></div>
 <div className="grid heroGrid"><Card className="hero"><div className="sectionHead"><div><span className="eyebrow"><Sparkles size={13}/> DECISION ENGINE</span><h2>Energy is only inefficient<br/><strong>when production says it is.</strong></h2></div><span className="score">AI CONFIDENCE <b>93%</b></span></div><div className="heroFlow"><div className="stage"><span>01</span><b>MEASURE</b><small>24 signals</small></div><div className="flowLine"/><div className="stage hot"><span>02</span><b>DETECT</b><small>3 anomalies</small></div><div className="flowLine"/><div className="stage"><span>03</span><b>EXPLAIN</b><small>root cause</small></div><div className="flowLine"/><div className="stage"><span>04</span><b>OPTIMIZE</b><small>₹4.06L / yr</small></div></div><button className="primary" onClick={()=>setTab('sim')}>Open optimization lab <ArrowUpRight size={16}/></button></Card>
 <Card className="baseline"><div className="sectionHead"><div><span className="eyebrow">BASELINE VS ACTUAL</span><h3>Energy intensity</h3></div><span className="badge good">5.2% below baseline</span></div><ResponsiveContainer width="100%" height={220}><AreaChart data={chart}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7dff9a" stopOpacity=".32"/><stop offset="100%" stopColor="#7dff9a" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#173329"/><XAxis dataKey="name" stroke="#68867a" tick={{fontSize:10}}/><YAxis stroke="#68867a" tick={{fontSize:10}} domain={['dataMin-20','dataMax+20']}/><Tooltip contentStyle={{background:'#08120f',border:'1px solid #204538',borderRadius:12}}/><Line type="monotone" dataKey={()=>data.kpi.baselineSec} stroke="#48685c" strokeDasharray="5 5" dot={false}/><Area type="monotone" dataKey="sec" stroke="#7dff9a" fill="url(#g)" strokeWidth={2}/></AreaChart></ResponsiveContainer></Card></div>
 <div className="grid lower"><Card><div className="sectionHead"><div><span className="eyebrow">AI WATCHLIST</span><h3>Events requiring attention</h3></div><button className="textBtn" onClick={()=>setTab('ai')}>View all <ArrowUpRight size={14}/></button></div>{alerts.slice(0,3).map(a=><div className="alertRow" key={a.id}><div className={`severity ${a.severity.toLowerCase()}`}><AlertTriangle size={15}/></div><div><b>{a.title}</b><small>{a.asset} · {a.impactKwh} kWh exposure · {a.confidence}% confidence</small></div><span className="time">NOW</span></div>)}</Card><Card><div className="sectionHead"><div><span className="eyebrow">OPTIMIZATION QUEUE</span><h3>Actions with measurable impact</h3></div></div>{recs.slice(0,3).map(r=><div className="recRow" key={r.id}><div className="recIcon"><Lightbulb size={15}/></div><div><b>{r.title}</b><small>−{r.secReductionPct}% SEC · {money(r.annualSavingInr)}/yr · {r.confidence}% confidence</small></div><span className="priority">{r.priority}</span></div>)}</Card></div>
 <div className="ribbon"><div><span className="eyebrow">THE DIFFERENCE</span><b>Not an energy meter. A production-aware energy decision system.</b></div><div className="ribbonSteps"><span>Telemetry</span><b>→</b><span>Baseline</span><b>→</b><span>Root cause</span><b>→</b><span>Action</span><b>→</b><span>Verified ROI</span></div></div>
 </div>}
function Twin(){return <div className="page"><Card className="twinCard"><div className="sectionHead"><div><span className="eyebrow">LIVE DIGITAL TWIN</span><h2>Production line energy map</h2></div><span className="live"><span/> 6 assets streaming</span></div><div className="factoryMap"><div className="mapGrid"/>{[['Raw material','7.9 t/h','raw',14,46],['Induction Furnace #02','612 kW','furnace',35,30],['Casting Cell','98.1% yield','cast',56,55],['Finishing','94% load','finish',76,34],['Edge Gateway','24 signals','edge',55,78]].map(([name,val,cl,x,y])=><div className={`machine ${cl}`} style={{left:x+'%',top:y+'%'}} key={name}><div className="machinePulse"/><span>{name}</span><b>{val}</b></div>)}<div className="path p1"/><div className="path p2"/><div className="path p3"/><div className="path p4"/></div><div className="twinLegend"><span><i className="greenDot"/> Healthy</span><span><i className="amberDot"/> Attention</span><span><i className="blueDot"/> Data path</span><span><GitBranch size={14}/> MQTT / OPC-UA</span></div></Card></div>}
function Analytics({chart,data}){return <div className="page"><div className="grid two"><Card><div className="sectionHead"><div><span className="eyebrow">24H TREND</span><h3>Energy vs production</h3></div></div><ResponsiveContainer width="100%" height={320}><LineChart data={chart}><CartesianGrid stroke="#173329" strokeDasharray="3 3"/><XAxis dataKey="name" stroke="#68867a"/><YAxis yAxisId="l" stroke="#68867a"/><YAxis yAxisId="r" orientation="right" stroke="#68867a"/><Tooltip contentStyle={{background:'#08120f',border:'1px solid #204538',borderRadius:12}}/><Line yAxisId="l" type="monotone" dataKey="energy" stroke="#7dff9a" strokeWidth={2.5} dot={false}/><Line yAxisId="r" type="monotone" dataKey="prod" stroke="#62c7ff" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></Card><Card><div className="sectionHead"><div><span className="eyebrow">LOSS TREE</span><h3>Where the energy goes</h3></div></div><div className="lossTree">{[['Furnace thermal losses',42,'hot'],['Compressor system',24,'mid'],['Motors & drives',19,'low'],['Idle / standby',15,'idle']].map(([n,v,c])=><div className="loss" key={n}><div><b>{n}</b><span>{v}%</span></div><div className="bar"><i className={c} style={{width:v*2+'%'}}/></div></div>)}</div><div className="insight"><Sparkles size={17}/><div><b>Model insight</b><p>Furnace idle time and compressor pressure explain <strong>67%</strong> of the avoidable energy deviation in the current operating window.</p></div></div></Card></div><Card><div className="sectionHead"><div><span className="eyebrow">PROCESS HEALTH</span><h3>Production constraints</h3></div></div><div className="constraintGrid">{[['Throughput','8.34 t','ON TARGET'],['Quality','98.2%','STABLE'],['Power factor','0.96','HEALTHY'],['Downtime','7.8 min','LOW']].map(x=><div className="constraint" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></Card></div>}
function AI({alerts,recs}){return <div className="page"><div className="aiBanner"><div className="aiOrb"><BrainCircuit size={34}/></div><div><span className="eyebrow">EXPLAINABLE AI</span><h2>Operator-grade intelligence, not black-box magic.</h2><p>Every recommendation is tied to process signals, production context, estimated impact and a confidence score.</p></div></div><div className="grid two"><Card><div className="sectionHead"><div><span className="eyebrow">ACTIVE EVENTS</span><h3>Detection queue</h3></div><span className="badge danger">3 open</span></div>{alerts.map(a=><div className="aiAlert" key={a.id}><div className={`severity ${a.severity.toLowerCase()}`}><AlertTriangle size={16}/></div><div className="aiBody"><div className="aiTitle"><b>{a.title}</b><span>{a.confidence}% confidence</span></div><small>{a.asset}</small><p>{a.detail}</p><div className="evidence"><span>Impact <b>{a.impactKwh} kWh</b></span><span>Evidence <b>6 signals</b></span><span>State <b>Actionable</b></span></div></div></div>)}</Card><Card><div className="sectionHead"><div><span className="eyebrow">ROOT-CAUSE GRAPH</span><h3>Furnace #02 deviation</h3></div></div><div className="rootGraph"><div className="rootNode mainNode">SEC +8.6%</div><div className="rootArrow">↓</div><div className="rootNode">Furnace idle +4.4 min</div><div className="rootNode">Heat transition +2.1 min</div><div className="rootNode">Compressor +0.9 bar</div></div><div className="confidence"><span>Model confidence</span><b>93%</b><div><i style={{width:'93%'}}/></div></div></Card></div><div className="recommendations">{recs.map(r=><Card className="recommend" key={r.id}><div className="recHeader"><span className="recNumber">{r.id}</span><span className="priority">{r.priority}</span></div><h3>{r.title}</h3><p>{r.rationale}</p><div className="recMetrics"><div><b>−{r.secReductionPct}%</b><small>SEC</small></div><div><b>{money(r.annualSavingInr)}</b><small>annual saving</small></div><div><b>{r.paybackMonths} mo</b><small>payback</small></div></div><button className="secondary">Review action <ArrowUpRight size={14}/></button></Card>)}</div></div>}
function Simulator({sim,setSim,out,run}){return <div className="page"><div className="simHero"><div><span className="eyebrow"><SlidersHorizontal size={13}/> CONSTRAINED OPTIMIZATION</span><h2>Change the process.<br/><strong>See the energy consequence.</strong></h2><p>Move the sliders. The model recalculates SEC, energy reduction, carbon impact and financial value while protecting quality constraints.</p></div><div className="simResult"><span>PROJECTED SEC</span><b>{out?.projectedSec?.toFixed?.(1)||'—'}</b><small>kWh / tonne</small></div></div><div className="grid two"><Card><div className="controls">{[['idle','Furnace idle',4,16,.1,'min'],['pressure','Compressor pressure',6,8,.1,'bar'],['cycle','Cycle duration',28,42,1,'min'],['target','Production target',6,12,.1,'t/batch']].map(([k,l,min,max,step,u])=><label key={k}><div><span>{l}</span><b>{sim[k]} {u}</b></div><input type="range" min={min} max={max} step={step} value={sim[k]} onChange={e=>setSim({...sim,[k]:Number(e.target.value)})}/><div className="range"><span>{min}</span><span>{max}</span></div></label>)}<button className="primary wide" onClick={run}><Play size={16}/> Run scenario</button></div></Card><Card><div className="sectionHead"><div><span className="eyebrow">SCENARIO OUTPUT</span><h3>Expected business impact</h3></div></div>{out?<div className="scenario"><div className="scenarioMain"><b>{out.energyReductionPct.toFixed(1)}%</b><span>energy reduction</span></div><div className="scenarioGrid"><div><b>{money(out.annualSavingInr)}</b><small>annual saving</small></div><div><b>{Math.round(out.co2ReductionKg)} kg</b><small>CO₂ reduction</small></div><div><b className={out.qualityConstraintMet?'ok':'bad'}>{out.qualityConstraintMet?'PASS':'CHECK'}</b><small>quality guardrail</small></div></div><div className="guard"><ShieldCheck size={16}/><span>{out.qualityConstraintMet?'Scenario stays inside modeled production/quality constraints.':'Scenario violates a modeled operating constraint — adjust before deployment.'}</span></div></div>:<div className="empty"><Sparkles size={28}/><b>Ready to simulate</b><span>Run a scenario to generate a quantified recommendation.</span></div>}</Card></div></div>}
function ROI({data}){const annual=406000;return <div className="page"><div className="roiTop"><div><span className="eyebrow">BUSINESS CASE</span><h2>Make the energy case boardroom-ready.</h2><p>Every technical intervention rolls up into financial and carbon impact.</p></div><div className="roiBig"><span>MODELED ANNUAL VALUE</span><b>{money(annual)}</b></div></div><div className="grid four">{[['Deployment','₹2.00L','pilot cost'],['Payback','3.8 mo','modeled'],['Energy','80,000 kWh','annual opportunity'],['Carbon','56.8 t','CO₂ / year']].map(x=><Card className="roiCard" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></Card>)}</div><Card><div className="sectionHead"><div><span className="eyebrow">SCALE PATH</span><h3>From one line to a manufacturing network</h3></div></div><div className="scale">{[['01','0–3 months','Pilot','Meters + gateway + baseline'],['02','3–9 months','Factory-wide','SCADA / MES integration'],['03','9–24 months','Multi-site','Fleet benchmarking + ERP']].map((x,i)=><div className="scaleStep" key={x[0]}><span>{x[0]}</span><small>{x[1]}</small><b>{x[2]}</b><p>{x[3]}</p>{i<2&&<i>→</i>}</div>)}</div></Card><div className="techStack"><span>JAVA 25</span><span>SPRING BOOT 4</span><span>REACT + VITE</span><span>H2 / POSTGRES READY</span><span>MQTT / OPC-UA READY</span><span>VERCEL + RAILWAY</span></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
